//! Embedded CWE taxonomy. Bytes are compiled into the binary via `include_bytes!`
//! so no filesystem access is needed at runtime.

use std::sync::OnceLock;

use crate::Taxonomy;

const TAXONOMY_BYTES: &[u8] = include_bytes!("../data/cwe-tree-v4.19.1.json");

static TAXONOMY: OnceLock<Taxonomy> = OnceLock::new();

/// Return the embedded CWE taxonomy. Parsed lazily on first call and cached.
///
/// Panics if the embedded JSON is malformed. This is a build-time invariant:
/// the JSON is generated by `compile-taxonomy` and committed. If this panics,
/// the committed data is corrupt.
pub fn embedded() -> &'static Taxonomy {
    TAXONOMY.get_or_init(|| {
        Taxonomy::from_json(TAXONOMY_BYTES).expect("embedded CWE taxonomy must parse")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_loads_and_contains_known_cwes() {
        let tx = embedded();
        // View must match what we generated.
        assert_eq!(tx.view(), "1000");
        // Sanity: CWE-89 (SQL Injection) exists in view 1000.
        let c89 = tx.expand(89);
        assert!(c89.contains(&89), "CWE-89 closure missing self");
        assert!(c89.len() >= 2, "CWE-89 should have at least one descendant");
        // Unknown id falls through.
        assert_eq!(tx.expand(999_999), vec![999_999]);
    }
}
